spring:
  application:
    name: micro-test
  datasource:
    url: jdbc:h2:mem:transferenciasdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: false
  h2:
    console:
      enabled: true

server:
  port: 8080

library:
  openapi:
    spec-path: src/main/resources/openapi.yaml
    output-dir: target/generated-sources/openapi
    base-package: com.example.transferencias.api
    enabled: true
